package com.example.view.AdminView.Students;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.DateField;
import com.vaadin.ui.FormLayout;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AdminAddStudentForm extends FormLayout {
	protected TextField nom;
	protected TextField cognom;
	protected DateField fecha;
	protected TextField teléfons;
	protected TextField emails;
	protected NativeSelect grup;
	protected Button aceptarButton;
	protected Button cancelarButton;

	public AdminAddStudentForm() {
		Design.read(this);
	}
}
