package com.example.view.AdminView.Reports;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class AdminReportCSVUpload extends CssLayout {
	protected VerticalLayout mainTrimestral;
	protected Label txtUpTrimestral;
	protected HorizontalLayout hTrimestral;
	protected Button generateReportTrimestre1;
	protected Button generateReportTrimestre2;
	protected Button generateReportTrimestre3;
	protected VerticalLayout mainTotal;
	protected Label txtUpTotal;
	protected Button generateReportTotal;

	public AdminReportCSVUpload() {
		Design.read(this);
	}
}
