package com.example.Templates;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.Button;
import com.vaadin.ui.CssLayout;
import com.vaadin.ui.HorizontalLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class MainView extends HorizontalLayout {
	protected HorizontalLayout menuTitle;
	protected Label menuTitleLabel;
	protected Button menuToggle;
	protected CssLayout menuItems;
	protected VerticalLayout vImage;
	protected Label wellcome;
	protected Button sep;
	protected Button warning;
	protected Button groupsTutor;
	protected Button mevesAmonestacions;
	protected Button sep3;
	protected Button students;
	protected Button tutors;
	protected Button teachers;
	protected Button groups;
	protected Button usuaris;
	protected Button sep4;
	protected Button amonestacions;
	protected Button charts;
	protected Button informes;
	protected Button cargarCSV;
	protected Button configuracio;
	protected Button sep5;
	protected Button ficurs;
	protected Button logout;
	protected VerticalLayout content;

	public MainView() {
		Design.read(this);
	}
}
