package com.example.Templates;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.annotations.DesignRoot;
import com.vaadin.ui.AbsoluteLayout;
import com.vaadin.ui.Button;
import com.vaadin.ui.NativeSelect;
import com.vaadin.ui.OptionGroup;
import com.vaadin.ui.TextArea;
import com.vaadin.ui.TextField;
import com.vaadin.ui.declarative.Design;

/** 
 * !! DO NOT EDIT THIS FILE !!
 * 
 * This class is generated by Vaadin Designer and will be overwritten.
 * 
 * Please make a subclass with logic and additional interfaces as needed,
 * e.g class LoginView extends LoginDesign implements View { … }
 */
@DesignRoot
@AutoGenerated
@SuppressWarnings("serial")
public class NewWarning extends AbsoluteLayout {
	public TextField nom;
	public TextField cognoms;
	public NativeSelect circunstancia;
	public OptionGroup accio;
	public OptionGroup motiu;
	public TextArea amotius;
	public NativeSelect caracter;
	public TextField tutor;
	public OptionGroup motiu2;
	public Button baceptar;
	public Button bcancelar;
	public TextField grup;
	public TextField materia;

	public NewWarning() {
		Design.read(this);
	}
}
